variable "tenant" {}
variable "name" {}
variable "environment" {}
variable "vpc_id" {}
variable "cidr_block" {}
variable "pvt_subnet_ids" {}
variable "alb_dns_name" {}
variable "alb_zone_id" {}
variable "alb_https" {}
variable "hosted_zone" {}
variable "ecs_exec_role" {}
variable "cluster_id" {}
variable "cluster_arn" {}
variable "cluster_name" {}
variable "service" {}
variable "autoscaling" {}
variable "cpu" {}
variable "memory" {}
variable "port" {}
variable "parameters" {}
variable "desired_count" {}
variable "hc_grace_period" {}
variable "deploy_circuit_breaker" {}
variable "platform_version" {}
variable "deploy_url" {}
variable "predencence" {}
variable "deregistration_delay" {}
variable "healthcheck_path" {}
variable "healthcheck_interval" {}
variable "healthcheck_timeout" {}
variable "healthcheck_pos_threshold" {}
variable "healthcheck_neg_threshold" {}
variable "additional_role_policies" {}